// The art bundle format (docs/ART.md), as TypeScript types. Pure: no DOM, no
// Node. Shared by the runtime registry, the Art Lab and the bundle test.

import type { SpeciesAnim } from "../contracts";

/** Bundle kinds, named after their folders under public/art/. */
export const BUNDLE_KINDS = ["species", "tilesets", "structures", "characters", "sets"] as const;
export type BundleKind = (typeof BUNDLE_KINDS)[number];

/** The JSON file that marks a bundle folder, and its `format` string. */
export const BUNDLE_JSON: Record<BundleKind, { file: string; format: string }> = {
  species: { file: "species.json", format: "verdant.species/1" },
  tilesets: { file: "tileset.json", format: "verdant.tileset/1" },
  structures: { file: "structure.json", format: "verdant.structure/1" },
  characters: { file: "character.json", format: "verdant.character/1" },
  sets: { file: "set.json", format: "verdant.imageset/1" },
};
export const PACK_FORMAT = "verdant.pack/1";
export const INDEX_FORMAT = "verdant.artindex/1";

export type SourceInfo =
  | { kind: "generated"; tool: string }
  | { kind: "edited" }
  | { kind: "imported"; from: string };

export interface SpeciesBundle {
  format: "verdant.species/1";
  id: string;
  palette: string[];
  sport?: string[];
  /** front: 1–8 files (front … front__8); back: 1; icon: 1–2. */
  frames: { front: string[]; back: string[]; icon: string[] };
  /** Optional Crystal-style animation (front frame indexes, 60 fps ticks). */
  anim?: SpeciesAnim;
  credits?: string;
  source?: SourceInfo;
  notes?: string;
}

/** A cell number (static) or 1–2 cell numbers (animation frames 1 and 2). */
export type TileRef = number | number[];
export interface TileDef {
  base: TileRef;
  alts?: TileRef[];
  masks?: Record<string, TileRef>;
}
export interface TilesetBundle {
  format: "verdant.tileset/1";
  id: string;
  name?: string;
  tileSize: number;
  sheet: string;
  columns: number;
  tiles: Record<string, TileDef>;
  credits?: string;
  source?: SourceInfo;
}

export interface StructureBundle {
  format: "verdant.structure/1";
  id: string;
  image: string;
  size: [number, number];
  credits?: string;
  source?: SourceInfo;
}

export interface CharacterBundle {
  format: "verdant.character/1";
  id: string;
  sheet: string;
  frame: [number, number];
  rows: string[];
  columns: string[];
  credits?: string;
  source?: SourceInfo;
}

export interface ImageSetEntry { file: string; size?: [number, number]; source?: SourceInfo; credits?: string }
export interface ImageSetBundle {
  format: "verdant.imageset/1";
  id: string;
  logicalDir: string;
  images: Record<string, ImageSetEntry>;
  credits?: string;
}

export interface PackManifest {
  format: "verdant.pack/1";
  id: string;
  name: string;
  description?: string;
  author?: string;
}

export type BundleJson = SpeciesBundle | TilesetBundle | StructureBundle | CharacterBundle | ImageSetBundle;

/** Files per bundle id, for one tree (the base tree, or one pack). */
export type IndexTree = Record<BundleKind, Record<string, string[]>>;
export interface IndexPack extends IndexTree { name: string; description: string; author: string }
/** public/art/index.json (generated by tools/art/index.mjs). */
export interface ArtIndex extends IndexTree {
  format: typeof INDEX_FORMAT;
  packs: Record<string, IndexPack>;
  /** Transitional: legacy files under public/assets/ (logical paths). */
  legacy: string[];
}

export function emptyIndex(): ArtIndex {
  return {
    format: INDEX_FORMAT, species: {}, tilesets: {}, structures: {}, characters: {}, sets: {}, packs: {}, legacy: [],
  };
}

/**
 * One bundle JSON as found on disk / over the network, before merging.
 * `pack` is null for the base tree. `json` is undefined when the file failed
 * to load or parse (`error` says why).
 */
export interface RawBundle {
  kind: BundleKind;
  id: string;
  pack: string | null;
  files: string[];
  json?: unknown;
  error?: string;
}

/** Folder (relative to the site root, trailing slash) that holds a bundle's files. */
export function bundleDir(kind: BundleKind, id: string, pack: string | null, artRoot = "art/"): string {
  return pack ? `${artRoot}packs/${pack}/${kind}/${id}/` : `${artRoot}${kind}/${id}/`;
}
export function bundleJsonUrl(kind: BundleKind, id: string, pack: string | null, artRoot = "art/"): string {
  return bundleDir(kind, id, pack, artRoot) + BUNDLE_JSON[kind].file;
}

/** Every raw bundle the index lists (JSON not yet loaded). */
export function rawBundlesOf(index: ArtIndex): RawBundle[] {
  const out: RawBundle[] = [];
  for (const kind of BUNDLE_KINDS) {
    for (const [id, files] of Object.entries(index[kind] ?? {})) out.push({ kind, id, pack: null, files });
  }
  for (const [pack, tree] of Object.entries(index.packs ?? {})) {
    for (const kind of BUNDLE_KINDS) {
      for (const [id, files] of Object.entries(tree[kind] ?? {})) out.push({ kind, id, pack, files });
    }
  }
  return out;
}

/** Normalise a ref into its frame list (1 or 2 cells). */
export function refCells(ref: TileRef): number[] {
  return Array.isArray(ref) ? ref : [ref];
}
