"""Write src/assets/manifest.ts: ASSET_PATHS = every image under public/assets.

Paths are relative to the site root ("assets/tiles/grass.png"), sorted, so
the engine can preload them. Non-image files (CREDITS.md) are skipped.
Also checks that every asset the contracts require exists at the right size.

  python3 tools/art/build_manifest.py        (needs only Pillow)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
PUBLIC = ROOT / "public"
ASSETS = PUBLIC / "assets"
IDS = ROOT / "src" / "contracts" / "ids.ts"
OUT = ROOT / "src" / "assets" / "manifest.ts"


def const_list(src: str, name: str) -> list[str]:
    m = re.search(rf"export const {name} = \[(.*?)\] as const", src, re.S)
    body = re.sub(r"//[^\n]*", "", m.group(1))
    return re.findall(r'"([a-z0-9_]+)"', body)


def const_keys(src: str, name: str) -> list[str]:
    m = re.search(rf"export const {name} = \{{(.*?)\n\}} as const", src, re.S)
    body = re.sub(r"//[^\n]*", "", m.group(1))
    return re.findall(r"^\s*([a-z0-9_]+)\s*:", body, re.M)


def required() -> dict[str, tuple[int, int]]:
    """path -> (w, h) every file the contracts promise."""
    src = IDS.read_text()
    req: dict[str, tuple[int, int]] = {}
    for sid in const_list(src, "SPECIES_IDS"):
        req[f"assets/species/{sid}/front.png"] = (56, 56)
        req[f"assets/species/{sid}/back.png"] = (48, 48)
        req[f"assets/species/{sid}/icon.png"] = (16, 16)
        req[f"assets/species/{sid}/icon__2.png"] = (16, 16)
    for t in const_keys(src, "TILES"):
        req[f"assets/tiles/{t}.png"] = (16, 16)
    for t in ("water", "tall_grass", "flowers"):
        req[f"assets/tiles/{t}__2.png"] = (16, 16)
    for m in re.finditer(r"^\s*([a-z_]+):\s*\{ w: (\d+), h: (\d+)", re.search(
            r"export const STRUCTURES = \{(.*?)\n\} as const", src, re.S).group(1), re.M):
        req[f"assets/structures/{m.group(1)}.png"] = (int(m.group(2)) * 16, int(m.group(3)) * 16)
    for c in const_list(src, "CHARACTERS"):
        req[f"assets/characters/{c}.png"] = (48, 64)
    for p in const_list(src, "TRAINER_PORTRAITS"):
        req[f"assets/trainers/{p}.png"] = (48, 48) if p == "player_back" else (56, 56)
    for i in const_list(src, "REQUIRED_ITEMS"):
        req[f"assets/items/{i}.png"] = (16, 16)
    req["assets/ui/title.png"] = (160, 144)
    for n in ("title_logo", "pod", "pod_open", "mark_bramble", "mark_sundew", "battle_ground"):
        req[f"assets/ui/{n}.png"] = (0, 0)   # any size
    return req


def main() -> int:
    paths = sorted(p.relative_to(PUBLIC).as_posix() for p in ASSETS.rglob("*.png"))
    problems = []
    for path, (w, h) in required().items():
        f = PUBLIC / path
        if not f.exists():
            problems.append(f"missing {path}")
            continue
        if w:
            size = Image.open(f).size
            if size != (w, h):
                problems.append(f"{path} is {size[0]}x{size[1]}, want {w}x{h}")
    title_logo = ASSETS / "ui" / "title_logo.png"
    if title_logo.exists() and Image.open(title_logo).width > 160:
        problems.append("title_logo wider than 160")

    lines = ",\n".join(f'  "{p}"' for p in paths)
    OUT.write_text(
        "// GENERATED by tools/art/build_manifest.py - do not edit by hand.\n"
        "// Every image under public/assets, as site-root-relative paths, for preloading.\n"
        f"export const ASSET_PATHS: string[] = [\n{lines},\n];\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(paths)} images)")
    for p in problems:
        print("PROBLEM:", p)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
