"""Build the private interior and exterior LimeZu pack. Every output MUST be gitignored.

Use LIMEZU_INTERIORS / LIMEZU_EXTERIORS / LIMEZU_UI, or local.json next to
this script. --check compares generated bytes without writing anything.
No images or derivatives may leave public/art/packs/limezu/.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
sys.path.insert(0, str(HERE.parent))
from artkit.core import dumps, load_rgba, png_bytes, to_rgba
from artkit.sheets import assemble
from limezu.gen_props import OUTPUT, contract_text, prop_specs, mappings, FLOOR_PROPS
from limezu.geometry import measured_props, GARDEN, PORTICO_BOX
from limezu.terrain import outdoor_images
from PIL import Image

PACK = ROOT / "public" / "art" / "packs" / "limezu"
CREDITS = "LimeZu — Modern Interiors / Modern Exteriors, https://limezu.itch.io/. Licensed local use only; no redistribution."
TOOL = "tools/art/limezu/build_pack.py"
ROOM = "interiors:1_Interiors/16x16/Room_Builder_subfiles/"
FLOOR_BLOCKS = {
    "floor_wood": (0, 12), "floor_tile": (8, 2),
    "floor_greenhouse": (12, 16), "floor_marble": (0, 2),
}
# Tan 9-slice: source cells, not pixels. The lower border is drawn at the
# TOP of its source row; bottom quadrants use that row's upper 8 pixels.
BORDER_CELLS = {
    "tl": (35, 4), "top": (37, 3), "tr": (38, 4),
    "left": (35, 5), "fill": (40, 0), "right": (38, 5),
    "bl": (36, 1), "bottom": (37, 3), "br": (35, 1),
}


def mask_cells(mask: int) -> tuple[tuple[int, int], ...]:
    """9-slice cells for TL, TR, BL, BR quarters; N=1 E=2 S=4 W=8.

Two exposed adjacent sides use an outer corner; one uses its edge; no
exposed sides use dark fill. This also defines narrow and isolated walls.
"""
    if not 0 <= mask <= 15:
        raise ValueError("mask must be 0..15")
    names = []
    for vertical, horizontal, corner, edge_v, edge_h in (
        (1, 8, "tl", "top", "left"), (1, 2, "tr", "top", "right"),
        (4, 8, "bl", "bottom", "left"), (4, 2, "br", "bottom", "right"),
    ):
        v, h = not mask & vertical, not mask & horizontal
        names.append(corner if v and h else edge_v if v else edge_h if h else "fill")
    return tuple(BORDER_CELLS[name] for name in names)


WALL_MASK_CELLS = {mask: mask_cells(mask) for mask in range(16)}


def guarded(path: Path) -> None:
    """Check containment, symlinks AND Git's actual ignore decision before I/O."""
    try:
        relative = path.relative_to(PACK)
        path.resolve().relative_to(PACK.resolve())
        PACK.resolve().relative_to(ROOT.resolve() / "public" / "art" / "packs")
    except ValueError as e:
        raise RuntimeError(f"refusing output outside the local LimeZu pack: {path}") from e
    if PACK.is_symlink() or any(p.is_symlink() for p in (PACK, *[PACK / Path(*relative.parts[:n]) for n in range(1, len(relative.parts) + 1)])):
        raise RuntimeError(f"refusing symlink output: {path}")
    name = str(path.relative_to(ROOT)) + ("/" if path == PACK or path.is_dir() else "")
    result = subprocess.run(["git", "check-ignore", "-q", "--", name], cwd=ROOT)
    if result.returncode != 0:
        raise RuntimeError(f"refusing output Git does not ignore: {path.relative_to(ROOT)}")


def roots() -> dict[str, Path]:
    config = HERE / "local.json"
    local = json.loads(config.read_text()) if config.exists() else {}
    return {key: Path(value).expanduser().resolve() for key in ("interiors", "exteriors", "ui")
            if (value := os.environ.get(f"LIMEZU_{key.upper()}") or local.get(key))}


class Sources:
    def __init__(self, paths: dict[str, Path]):
        self.paths = paths
        self.cache = {}

    def sheet(self, source: str) -> Image.Image:
        if source not in self.cache:
            pack, sep, name = source.partition(":")
            if not sep or pack not in self.paths:
                raise ValueError(f"missing root for {source}: set LIMEZU_{pack.upper()} or local.json")
            path = (self.paths[pack] / name).resolve()
            if Path(name).is_absolute() or not path.is_relative_to(self.paths[pack]):
                raise ValueError(f"source escapes its root: {source}")
            self.cache[source] = Image.fromarray(load_rgba(path))
        return self.cache[source]

    def crop(self, source: str, box: tuple | list) -> Image.Image:
        sheet = self.sheet(source)
        x0, y0, x1, y1 = box
        if not (0 <= x0 < x1 <= sheet.width and 0 <= y0 < y1 <= sheet.height):
            raise ValueError(f"crop outside {source} ({sheet.size}): {box}")
        return sheet.crop(box)

    def tile(self, source: str, col: int, row: int) -> Image.Image:
        return self.crop(source, (col * 16, row * 16, (col + 1) * 16, (row + 1) * 16))


def padded_prop(crop: Image.Image, w: int, h: int) -> Image.Image:
    canvas = Image.new("RGBA", (w * 16, h * 16))
    if crop.width > canvas.width or crop.height > canvas.height:
        raise ValueError("prop exceeds contract geometry; regenerate props.ts")
    canvas.paste(crop, ((canvas.width - crop.width) // 2, canvas.height - crop.height))
    return canvas


def wall_tile(sources: Sources, mask: int) -> Image.Image:
    sheet = ROOM + "Room_Builder_borders_16x16.png"
    canvas = sources.tile(sheet, *BORDER_CELLS["fill"])
    for i, cell in enumerate(WALL_MASK_CELLS[mask]):
        x, y = (i % 2) * 8, (i // 2) * 8
        # Bottom border source occupies its upper half, unlike side/fill tiles.
        sy = 0 if i >= 2 and not mask & 4 else y
        piece = sources.tile(sheet, *cell).crop((x, sy, x + 8, sy + 8))
        canvas.alpha_composite(piece, (x, y))
    return canvas


def interior_images(sources: Sources) -> dict:
    images = {}
    floor_sheet = ROOM + "Room_Builder_Floors_16x16.png"
    for key, (col, row) in FLOOR_BLOCKS.items():
        cells = [(col + x, row + y) for y in range(2) for x in range(3)]
        base = (col + 1, row)
        cells.remove(base)
        images[key] = to_rgba(sources.tile(floor_sheet, *base))
        for n, cell in enumerate(cells, 1):
            images[f"{key}~{n}"] = to_rgba(sources.tile(floor_sheet, *cell))
    wall_sheet = ROOM + "Room_Builder_Walls_16x16.png"
    images["wall_face"] = to_rgba(sources.tile(wall_sheet, 1, 6))
    images["wall_face~1"] = to_rgba(sources.tile(wall_sheet, 2, 6))
    # N alone determines upper/lower; every mask is explicit for runtime lookup.
    for mask in range(16):
        images[f"wall_face@{mask}"] = to_rgba(sources.tile(wall_sheet, 2 if mask & 2 else 1, 7 if mask & 1 else 6))
    images["wall"] = to_rgba(wall_tile(sources, 15))
    for mask in range(16):
        images[f"wall@{mask}"] = to_rgba(wall_tile(sources, mask))
    return images


def json_bytes(value: object) -> bytes:
    return (dumps(value) + "\n").encode("utf-8")


def outputs(sources: Sources) -> dict[str, bytes]:
    mapping = mappings()
    prop_images, measured = measured_props(mapping, sources)
    for key in FLOOR_PROPS:
        if "prop_" + key in measured:
            measured["prop_" + key]["layer"] = "floor"
    if measured != prop_specs():
        raise ValueError("measured geometry is stale: run gen_props.py --measure")
    result = {"pack.json": json_bytes({"format": "verdant.pack/1", "id": "limezu", "name": "LimeZu",
              "description": "Locally imported Modern Interiors and Exteriors. Private licensed assets.", "author": "LimeZu"})}
    for id_, spec in prop_specs().items():
        entry = mapping[id_[5:]]
        img = prop_images[id_]
        original = entry["source"] is None and id_ not in {"prop_conservatory", "prop_house_small"}
        source = {"kind": "generated" if original else "imported", "tool": TOOL}
        if id_ == "prop_conservatory":
            source["parts"] = [{"from": GARDEN, "box": mapping["greenhouse"]["box"], "copies": 2}, {"from": GARDEN, "box": PORTICO_BOX}]
        elif not original:
            actual = mapping["harbour_house"] if id_ == "prop_house_small" else entry
            source.update({"from": actual["source"], "box": actual["box"]})
        prefix = f"structures/{id_}/"
        result[prefix + "structure.png"] = png_bytes(to_rgba(img))
        result[prefix + "structure.json"] = json_bytes({"format": "verdant.structure/1", "id": id_,
            "image": "structure.png", "size": [spec["w"], spec["h"]], "credits": CREDITS,
            "source": source})
    sheet, tiles, columns = assemble(interior_images(sources))
    result["tilesets/interior/sheet.png"] = png_bytes(sheet)
    result["tilesets/interior/tileset.json"] = json_bytes({"format": "verdant.tileset/1", "id": "interior",
        "name": "LimeZu interiors", "tileSize": 16, "sheet": "sheet.png", "columns": columns, "tiles": tiles,
        "credits": CREDITS, "source": {"kind": "imported", "tool": TOOL}})
    outdoor, blocks, terrains = outdoor_images(sources)
    # Override the existing owning bundle. A new catch-all bundle can lose
    # keys to alphabetically earlier base owners (notably city/paving).
    for tileset, keys in {"terrain": {"path", "dirt", "sand", "stone_path", "grass"},
                          "water": {"water"}, "city": {"paving"}}.items():
        selected = {stem: image for stem, image in outdoor.items() if stem.split("@")[0].split("~")[0].split("__")[0] in keys}
        sheet, tiles, columns = assemble(selected)
        result[f"tilesets/{tileset}/sheet.png"] = png_bytes(sheet)
        result[f"tilesets/{tileset}/tileset.json"] = json_bytes({"format": "verdant.tileset/1", "id": tileset,
            "name": "LimeZu outdoor ground", "tileSize": 16, "sheet": "sheet.png", "columns": columns,
            "tiles": tiles, "credits": CREDITS, "source": {"kind": "imported", "tool": TOOL}})
    result["terrain-classification.json"] = json_bytes({"blocks": blocks, "terrains": terrains,
        "animated_water": "water__2" in outdoor})
    return result


def local_index_bytes() -> bytes:
    # R1b indexer, read-only here: NEVER invoke its main(), which writes base too.
    code = 'import {buildLocalIndexes,formatIndex} from "./tools/art/index.mjs"; process.stdout.write(formatIndex(buildLocalIndexes().limezu));'
    return subprocess.run(["node", "--input-type=module", "-e", code], cwd=ROOT,
                          check=True, capture_output=True).stdout


def build(check: bool = False) -> int:
    guarded(PACK)
    if not OUTPUT.exists() or OUTPUT.read_text() != contract_text():
        raise ValueError("props.ts is stale: run tools/art/limezu/gen_props.py first")
    result = outputs(Sources(roots()))
    manifest = PACK / ".interior-files.json"
    old = json.loads(manifest.read_text()) if manifest.exists() else []
    stale = [PACK / name for name in old if name not in result]
    result[manifest.name] = json_bytes(sorted(result))
    # Preflight ALL destinations before the first write. This catches tracked
    # files and symlinks inside an otherwise ignored directory as well.
    for path in [*(PACK / name for name in result), *stale, PACK / "index.json"]:
        guarded(path)
    changed = [name for name, data in result.items() if not (PACK / name).is_file() or (PACK / name).read_bytes() != data]
    if check:
        if changed or any(p.exists() for p in stale):
            print("LimeZu pack is stale: run tools/art/limezu/build_pack.py")
            return 1
        if not (PACK / "index.json").exists() or (PACK / "index.json").read_bytes() != local_index_bytes():
            print("LimeZu local index is stale: run tools/art/limezu/build_pack.py")
            return 1
        print("LimeZu interiors, exteriors and local index are up to date")
        return 0
    for path in stale:
        if path.exists():
            path.unlink()
            if not any(path.parent.iterdir()):
                guarded(path.parent)
                path.parent.rmdir()
    for name in changed:
        path = PACK / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(result[name])
    index = local_index_bytes()
    if not (PACK / "index.json").exists() or (PACK / "index.json").read_bytes() != index:
        (PACK / "index.json").write_bytes(index)
    print(f"LimeZu: {len(prop_specs())} props; interior shell and outdoor ground; local index ({len(changed)} changed files)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        return build(args.check)
    except (OSError, ValueError, RuntimeError, subprocess.CalledProcessError) as e:
        print(f"LimeZu importer: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
