"""Generate public prop geometry from mapping coordinates, never source pixels."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
MAPPING = HERE / "mapping" / "interior_props.json"
OUTPUT = ROOT / "src" / "contracts" / "props.ts"
FLOOR_PROPS = {"rug_large", "rug_small", "window", "painting"}


def prop_specs(mapping: dict | None = None) -> dict:
    mapping = json.loads(MAPPING.read_text()) if mapping is None else mapping
    specs = {}
    for key, entry in sorted(mapping.items()):
        if entry["source"] is None:
            continue
        box = entry.get("box")
        if (not isinstance(box, list) or len(box) != 4 or
                any(type(v) is not int or v < 0 for v in box) or
                box[2] <= box[0] or box[3] <= box[1]):
            raise ValueError(f"{key}: expected a nonempty integer pixel box")
        w, h = (box[2] - box[0] + 15) // 16, (box[3] - box[1] + 15) // 16
        depth = max(1, h - 1)
        spec = {"w": w, "h": h, "footprint": {"x": 0, "y": h - depth, "w": w, "h": depth}}
        if key in FLOOR_PROPS:
            spec["layer"] = "floor"
        specs[f"prop_{key}"] = spec
    return specs


def contract_text() -> str:
    lines = ["// Generated by tools/art/limezu/gen_props.py. Geometry only; no licensed pixels.",
             'import type { StructureSpec } from "./ids";', "", "export const PROP_SPECS = {"]
    for key, spec in prop_specs().items():
        f = spec["footprint"]
        layer = ', layer: "floor"' if "layer" in spec else ""
        lines.append(f'  {key}: {{ w: {spec["w"]}, h: {spec["h"]}, footprint: {{ x: 0, y: {f["y"]}, w: {f["w"]}, h: {f["h"]} }}{layer} }},')
    return "\n".join(lines + ["} as const satisfies Record<string, StructureSpec>;", ""])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = contract_text()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != text:
            print("props.ts is stale: run tools/art/limezu/gen_props.py")
            return 1
    elif not OUTPUT.exists() or OUTPUT.read_text() != text:
        OUTPUT.write_text(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
