"""Generate public prop contracts from measured tile geometry (no source pixels).

--measure refreshes the geometry cache using the owner's local source sheets.
Ordinary regeneration and CI need only the public coordinate cache.
"""
from __future__ import annotations
import argparse
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
MAPPING = HERE / 'mapping' / 'interior_props.json'
GEOMETRY = HERE / 'mapping' / 'prop_geometry.json'
OUTPUT = ROOT / 'src' / 'contracts' / 'props.ts'
FLOOR_PROPS = {'rug_large', 'rug_small', 'window', 'painting', 'dock', 'flower_bed'}


def mappings():
    return {**json.loads(MAPPING.read_text()), **json.loads((HERE / 'mapping/exterior_props.json').read_text())}


def prop_specs():
    return json.loads(GEOMETRY.read_text())


def contract_text():
    lines = ['// Generated by tools/art/limezu/gen_props.py. Geometry only; no licensed pixels.',
             'import type { StructureSpec } from "./ids";', '', 'export const PROP_SPECS = {']
    for key, spec in prop_specs().items():
        value = json.dumps(spec, separators=(', ', ': '))
        value = re.sub(r'"([a-z]+)":', r'\1:', value).replace('{', '{ ').replace('}', ' }')
        lines.append(f'  {key}: {value},')
    return '\n'.join(lines + ['} as const satisfies Record<string, StructureSpec>;', ''])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--measure', action='store_true')
    args = parser.parse_args()
    if args.measure:
        if args.check:
            parser.error('--measure and --check are mutually exclusive')
        from build_pack import Sources, roots
        from geometry import measured_props
        _, specs = measured_props(mappings(), Sources(roots()))
        for key in FLOOR_PROPS:
            if 'prop_' + key in specs:
                specs['prop_' + key]['layer'] = 'floor'
        GEOMETRY.write_text(json.dumps(specs, indent=2) + '\n')
    text = contract_text()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != text:
            print('props.ts is stale: run tools/art/limezu/gen_props.py')
            return 1
    elif not OUTPUT.exists() or OUTPUT.read_text() != text:
        OUTPUT.write_text(text)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
