import type { MapDef } from "../../contracts";
import { OUTDOOR, when } from "../build";

export const council_arboretum: MapDef = {
  id: "council_arboretum", name: "ARBORETUM", outdoor: true, music: "small_town",
  border: "tree", legend: OUTDOOR,
  tiles: [
    "TTTTTTTTTTTTTTT:N:TTTTTTTTTTTTTTTT",
    "T..............:::...............T",
    "T..............:::...............T",
    "T..............:::...............T",
    "T..............:::...............T",
    "TLLLLLLLLLLLLLLLNLLLLLLLLLLLLLLLLT",
    "T................................T",
    "T................................T",
    "T................................T",
    "T................................T",
    "T...........@@@@@@...............T",
    "T...........@@@@@@...............T",
    "T...........@@@@@@...............T",
    "T...........@@@@@@...............T",
    "T................................T",
    "T................................T",
    "T................................T",
    "T...@@@@.........................T",
    "T...@@@@.........................T",
    "T...@@@@.........................T",
    "T................................T",
    "T................................T",
    "T...........................::::::",
    "T................................T",
    "T................................T",
    "T................................T",
    "T................................T",
    "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
  ],
  structures: [{ key: "conservatory", x: 12, y: 10 }, { key: "greenhouse", x: 4, y: 17 }],
  warps: [
    { x: 33, y: 22, to: "route_12", toX: 1, toY: 3, facing: "right" },
    { x: 6, y: 19, to: "arboretum_greenhouse", toX: 5, toY: 7, facing: "up" },
    { x: 15, y: 13, to: "council_hall", toX: 7, toY: 10, facing: "up" },
    { x: 16, y: 0, to: "elder_grove_1", toX: 15, toY: 28, facing: "up" },
  ],
  npcs: [
    { id: "grunt_arb_1", sprite: "grunt", x: 14, y: 7, facing: "down", trainer: "grunt_arb_1", sight: 1 },
    { id: "grunt_arb_2", sprite: "grunt", x: 18, y: 7, facing: "down", trainer: "grunt_arb_2", sight: 1 },
    { id: "grunt_arb_3", sprite: "grunt", x: 18, y: 3, facing: "left", trainer: "grunt_arb_3", sight: 1 },
    { id: "bram_arboretum", sprite: "bram", x: 21, y: 20, facing: "left", script: "ch10_bram_joins", visibleWhen: when({ bram_joined: false }) },
    { id: "rowan_arboretum", sprite: "vale", x: 17, y: 14, facing: "down", script: "ch10_end", visibleWhen: when({ beat_mercer: true }) },
  ],
  signs: [],
  triggers: [
    { x: 16, y: 1, script: "ch10_bram_joins", when: when({ bram_joined: false }) },
    { x: 15, y: 14, script: "ch10_council_door", when: when({ ch10_done: false }) },
    { x: 22, y: 20, script: "ch10_bram_joins", when: when({ bram_joined: false }) },
  ],
  onEnter: "ch10_arboretum_enter",
};
