import type { MapDef } from "../../contracts";
import { OUTDOOR } from "../build";

export const driftseed_isle: MapDef = {
  id: "driftseed_isle", name: "DRIFTSEED ISLE", outdoor: true, music: "small_town", ambient: "none",
  border: "volcanic_rock", legend: { ...OUTDOOR, ".": "salt_flat", "@": "salt_flat", A: "volcanic_rock", o: "volcanic_rock", ",": "cactus_scrub", "=": "pier", g: "dry_grass", z: "shell_scatter", D: "driftwood", K: "beach_rock" },
  tiles: [
    "AAAAAAAAAAAAAAAA~~AAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAA~~AAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAA~~AAAAAAAAAAAAAAAA",
    "AAsssssssssssss====sssssssssssssAA",
    "AAsssssssssssss====sssssssssssssAA",
    "AAszzz....gggKg====.zKz........sAA",
    "AAsDz@@@@.ggggg.::..zzz@@@@@@ggsAA",
    "AAszz@@@@.ggggg.::.ggg.@@@@@@glsAA",
    "AAszz@@@@.lggg..::.ggg.@@@@@@ggsAA",
    "AAs........ggg..::.ggg.@@@@@@ggsAA",
    "AAszzz:.....@@@@::.ggg....:..ggsAA",
    "AAszzz::::7.@@@@::.gKgg...:.zzzsAA",
    "AAszzzggg...@@@@::.gggg::::.zSzsAA",
    "AAszKzggg..6..:.::.9gggooooozzzsAA",
    "AAs...:::::::::::::::::o@@@@zzzsAA",
    "AAs...:::::::::::::::::o@@@@zzzsAA",
    "AAs.ggggggg.....::.ggggo@@@@zzzsAA",
    "AAs.lggggDggggg.::.gggg..:..zzzsAA",
    "AAs.......ggggK.NN.gggg.....zKzsAA",
    "AAs,,,,,,,,,....::.ggg.,,,,,,,.sAA",
    "AAs,,,,,,,,,ggg.::.ggg.,,,,,,,.sAA",
    "AAs,,,,,,,,,ggg.::.gDg.,,,,,,,.sAA",
    "AAs,,,,,,,,,ggg.::.ggg.,,,,,,,.sAA",
    "AAs,,,,,,,,,ggg.::.ggg.,,,,,,,.sAA",
    "AAs,,,,,,,,,gKg.::.....,,,,,,,.sAA",
    "AAszzKzzzzzz....::....zzzzzzDzzsAA",
    "AAssssssssssssssssssssssssssssssAA",
    "AAssssssssssssssssssssssssssssssAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  ],
  structures: [
    { key: "driftwood_hut", x: 5, y: 6 }, { key: "greenhouse", x: 12, y: 10 },
    { key: "adobe_conservatory", x: 23, y: 6 }, { key: "driftwood_hut", x: 24, y: 14 },
  ],
  warps: [
    { x: 16, y: 0, to: "route_8", toX: 18, toY: 38, facing: "up" },
    { x: 17, y: 0, to: "route_8", toX: 19, toY: 38, facing: "up" },
    { x: 14, y: 12, to: "driftseed_greenhouse", toX: 5, toY: 7, facing: "up" },
    { x: 26, y: 9, to: "driftseed_conservatory", toX: 7, toY: 16, facing: "up" },
    { x: 25, y: 16, to: "driftseed_vents", toX: 11, toY: 22, facing: "up" },
  ],
  npcs: [{ id: "isle_elder", sprite: "island_elder", x: 6, y: 9, facing: "down", movement: "static", script: "ch6_elder" }],
  signs: [{ x: 29, y: 12, text: "THE VENTS. South by the hut." }], triggers: [{ x: 6, y: 8, script: "ch6_elder" }], onEnter: "ch6_isle_enter",
  encounters: { grass: { rate: 12, slots: [
    { species: "pear_pad", minLevel: 21, maxLevel: 21, weight: 35 },
    { species: "padded_cactus", minLevel: 26, maxLevel: 30, weight: 25 },
    { species: "saguaro_pup", minLevel: 26, maxLevel: 29, weight: 20 },
    { species: "fireweed_shoot", minLevel: 26, maxLevel: 29, weight: 10 },
    { species: "vanilla_vine", minLevel: 26, maxLevel: 30, weight: 10 },
  ] } },
};
