import type { MapDef } from "../../contracts";
import { OUTDOOR } from "../build";

export const driftseed_isle: MapDef = {
  id: "driftseed_isle", name: "DRIFTSEED ISLE", outdoor: true, music: "small_town", ambient: "none",
  border: "volcanic_rock", legend: { ...OUTDOOR, ".": "salt_flat", "@": "salt_flat", A: "volcanic_rock", o: "volcanic_rock", ",": "cactus_scrub", "=": "pier" },
  tiles: [
    "AAAAAAAAAAAAAAAA~~AAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAA~~AAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAA~~AAAAAAAAAAAAAAAA",
    "AAsssssssssssss====sssssssssssssAA",
    "AAsssssssssssss====sssssssssssssAA",
    "AAs............====............sAA",
    "AAs..@@@@.......::.....@@@@@@..sAA",
    "AAs..@@@@.......::.....@@@@@@..sAA",
    "AAs..@@@@.......::.....@@@@@@..sAA",
    "AAs.............::.....@@@@@@..sAA",
    "AAs.........@@@@::.............sAA",
    "AAs.........@@@@::.............sAA",
    "AAs.........@@@@::.............sAA",
    "AAs.............::.....ooooo...sAA",
    "AAs...:::::::::::::::::o@@@@...sAA",
    "AAs...:::::::::::::::::o@@@@...sAA",
    "AAs.............::.....o@@@@...sAA",
    "AAs.............::.............sAA",
    "AAs.............NN.............sAA",
    "AAs,,,,,,,,,....::.....,,,,,,,.sAA",
    "AAs,,,,,,,,,....::.....,,,,,,,.sAA",
    "AAs,,,,,,,,,....::.....,,,,,,,.sAA",
    "AAs,,,,,,,,,....::.....,,,,,,,.sAA",
    "AAs,,,,,,,,,....::.....,,,,,,,.sAA",
    "AAs,,,,,,,,,....::.....,,,,,,,.sAA",
    "AAs.............::.............sAA",
    "AAssssssssssssssssssssssssssssssAA",
    "AAssssssssssssssssssssssssssssssAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  ],
  structures: [
    { key: "driftwood_hut", x: 5, y: 6 }, { key: "greenhouse", x: 12, y: 10 },
    { key: "adobe_conservatory", x: 23, y: 6 }, { key: "driftwood_hut", x: 24, y: 14 },
  ],
  warps: [
    { x: 16, y: 0, to: "route_8", toX: 18, toY: 38, facing: "up" },
    { x: 17, y: 0, to: "route_8", toX: 19, toY: 38, facing: "up" },
    { x: 14, y: 12, to: "driftseed_greenhouse", toX: 5, toY: 7, facing: "up" },
    { x: 26, y: 9, to: "driftseed_conservatory", toX: 7, toY: 16, facing: "up" },
    { x: 25, y: 16, to: "driftseed_vents", toX: 11, toY: 22, facing: "up" },
  ],
  npcs: [{ id: "isle_elder", sprite: "island_elder", x: 6, y: 9, facing: "down", movement: "static", script: "ch6_elder" }],
  signs: [], triggers: [{ x: 6, y: 8, script: "ch6_elder" }], onEnter: "ch6_isle_enter",
  encounters: { grass: { rate: 12, slots: [
    { species: "pear_pad", minLevel: 21, maxLevel: 21, weight: 35 },
    { species: "padded_cactus", minLevel: 26, maxLevel: 30, weight: 25 },
    { species: "saguaro_pup", minLevel: 26, maxLevel: 29, weight: 20 },
    { species: "fireweed_shoot", minLevel: 26, maxLevel: 29, weight: 10 },
    { species: "vanilla_vine", minLevel: 26, maxLevel: 30, weight: 10 },
  ] } },
};
