import { groveEncounters } from "./elder_grove_2";
import type { MapDef } from "../../contracts";
import { OUTDOOR, when } from "../build";

export const elder_grove_1: MapDef = {
  id: "elder_grove_1", name: "ELDER GROVE", outdoor: true, music: "sugarbush_grove",
  border: "aspen_tree",
  legend: { ...OUTDOOR, T: "aspen_tree", ".": "grove_floor", ",": "grove_grass", ":": "root_vein", N: "root_vein" },
  tiles: [
    "TTTTTTTTTTTTTTTNTTTTTTTTTTTTTT",
    "T.....TT.......:...........TTT",
    "T.....T........:::::..TTT..TTT",
    "T.,,,,.....:::::...:...T.....T",
    "T.,,,,.........:...:.........T",
    "T.,,,,.........:.............T",
    "T..............::::::::::::..T",
    "T.....................:::::..T",
    "T.TTTTTTTTTTTTTTTTTTTTTTT.:..T",
    "T.TTTTTTTTTTTTTTTTTTTTTTT.:..T",
    "T................TT.......:::T",
    "T...TT..:....TT...........:..T",
    "T...TTT.:....T............:..T",
    "T.......:.................:..T",
    "T..::::::::::::::::::::::::..T",
    "T..:................:........T",
    "T..:................:.TT.....T",
    "T..:.TTTTTTTTTTTTTTTTTTTTTTT.T",
    "T:::.TTTTTTTTTTTTTTTTTTTTTTT.T",
    "T..:..TT...............TTT...T",
    "T..:...................TT....T",
    "T..:::::::::::::.............T",
    "T..............:...:.........T",
    "T.........T....:...:...,,,,..T",
    "T.........TT...:::::...,,,,..T",
    "T..............:.......,,,,..T",
    "TT.........:::::.....TTT.....T",
    "TTT........:...:......TT.....T",
    "T..............:.............T",
    "TTTTTTTTTTTTTTT:TTTTTTTTTTTTTT",
  ],
  legendWhen: [{ when: when({ beat_shears_2: false }), legend: { N: "aspen_tree" } }],
  structures: [],
  warps: [
    { x: 15, y: 29, to: "council_arboretum", toX: 16, toY: 1, facing: "down" },
    { x: 15, y: 0, to: "elder_grove_2", toX: 15, toY: 28, facing: "up" },
  ],
  npcs: [
    { id: "grunt_g1_1", sprite: "grunt", x: 7, y: 24, facing: "right", trainer: "grunt_g1_1", sight: 1 },
    { id: "grunt_g1_2", sprite: "grunt", x: 25, y: 13, facing: "left", trainer: "grunt_g1_2", sight: 1 },
    { id: "shears_2", sprite: "shears", x: 13, y: 3, facing: "down", script: "shears_2" },
    { id: "bram_ring_1", sprite: "bram", x: 17, y: 3, facing: "left", script: "ch10_bram_ring_1", visibleWhen: when({ bram_joined: true, beat_mercer: false }) },
  ],
  signs: [], triggers: [],
  encounters: groveEncounters,
};
