import type { MapDef } from "../../contracts";
import { OUTDOOR, when } from "../build";

export const larchmere: MapDef = {
  id: "larchmere", name: "LARCHMERE", outdoor: true, music: "small_town", ambient: "none",
  border: "tree", legend: OUTDOOR,
  tiles: [
    "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
    "T..................................T",
    "T..................................T",
    "T..................................T",
    "T..................................T",
    "T..................................T",
    "T......................@@@@@@......T",
    "T......................@@@@@@......T",
    "T......................@@@@@@......T",
    "T...@@@@....@@@@.......@@@@@@......T",
    "T...@@@@....@@@@...................T",
    "T...@@@@....@@@@...................T",
    "T..................................T",
    "T..................................T",
    "T..................................T",
    "T..................................T",
    "T..................................T",
    "T..:::::::::::::::::::::::::::::::::",
    "T..:::::::::::::::::::::::::::::::::",
    "T..................................T",
    "T.......................@@@@@......T",
    "T................::.....@@@@@......T",
    "T................::.....@@@@@......T",
    "T................::................T",
    "T................::................T",
    "T................::................T",
    "T................::................T",
    "T................::................T",
    "T................::................T",
    "TTTTTTTTTTTTTTTTT::TTTTTTTTTTTTTTTTT",
  ],
  structures: [
    { key: "greenhouse", x: 4, y: 9 }, { key: "market", x: 12, y: 9 },
    { key: "conservatory", x: 23, y: 6 }, { key: "lodge", x: 24, y: 20 },
  ],
  warps: [
    { x: 17, y: 29, to: "route_9", toX: 14, toY: 1, facing: "down" },
    { x: 18, y: 29, to: "route_9", toX: 15, toY: 1, facing: "down" },
    { x: 35, y: 17, to: "bloom_lake", toX: 1, toY: 17, facing: "right" },
    { x: 35, y: 18, to: "bloom_lake", toX: 1, toY: 18, facing: "right" },
    { x: 6, y: 11, to: "larchmere_greenhouse", toX: 5, toY: 7, facing: "up" },
    { x: 13, y: 11, to: "larchmere_market", toX: 6, toY: 7, facing: "up" },
    { x: 26, y: 9, to: "larchmere_conservatory", toX: 7, toY: 18, facing: "up" },
    { x: 26, y: 22, to: "larchmere_lodge", toX: 6, toY: 10, facing: "up" },
  ],
  npcs: [], signs: [],
  triggers: [{ x: 26, y: 10, script: "ch7_cons7_door", when: when({ lake_calmed: false }) }],
  onEnter: "ch7_town_enter",
};
