import type { MapDef } from "../../contracts";
import { OUTDOOR, when } from "../build";

export const larchmere: MapDef = {
  id: "larchmere", name: "LARCHMERE", outdoor: true, music: "alpine", ambient: "none",
  border: "larch_tree", legend: { ...OUTDOOR, T: "larch_tree", z: "frozen_shore" },
  tiles: [
    "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
    "TTT..........TTTTTTTTT.......TTTTTTT",
    "T.............TTTTTT.........TTTTTTT",
    "T.@@@@7.@@@@3........y*........TTTTT",
    "T.@@@@8.@@@@....*f*............TTTTT",
    "T.@@@@..@@@@.3...9.............zzzzT",
    "Tf.:yy*f.:*fy.......f.y@@@@@@f.zzzzT",
    "T##N#####N###.........f@@@@@@y.zzzzT",
    "T..:::::::::::::......y@@@@@@fzzzzzT",
    "Ty..@@@@.6..@@@@7......@@@@@@.zzzzzT",
    "Tf..@@@@..**@@@@::::::::::::..zzzzzT",
    "T...@@@@....@@@@:6*..y6:6.::.6zzzzzT",
    "T.:::::::::::::::..@@..:..::..zzzzzT",
    "T.:::::::::::::::9.@@.9:*.::..zzzzzT",
    "T...............:......:..::y.zzzzzT",
    "T...............:Sf..*6:..::..zzzzzT",
    "T...............::::::::::::..zzzzzT",
    "T:::::::::::::::::::::::::::::::::::",
    "T:::::::::::::::::::::::::::::::::::",
    "T###############.::..........:zzzzzT",
    "T..@@@@..@@@@....::...4.@@@@@:zzzzzT",
    "TG.@@@@k.@@@@*...::...3.@@@@@:zzzzzT",
    "TG.@@@@k.@@@@f7..::....8@@@@@:zzzzzT",
    "T...:.....:......::::::::::::::zzzzT",
    "T.:::::::::::::::::....y*y.f*fz@@@@T",
    "T3.....y*........::...........z@@@@T",
    "TTT............o.::.....o.....z@@@@T",
    "TTTTTT.....TTTTT.::.TTTT....3.zzzzzT",
    "TTTTTT.....TTTTT.::.TTTT......zzzzzT",
    "TTTTTTTTTTTTTTTTT::TTTTTTTTTTTTTTTTT",
  ],
  structures: [
    { key: "greenhouse", x: 4, y: 9 }, { key: "market", x: 12, y: 9 },
    { key: "frost_conservatory", x: 23, y: 6 }, { key: "alpine_lodge", x: 24, y: 20 },
    { key: "chalet", x: 2, y: 3 }, { key: "chalet", x: 8, y: 3 },   // doors 3,5 and 9,5
    { key: "chalet", x: 3, y: 20 }, { key: "chalet", x: 9, y: 20 }, // doors 4,22 and 10,22
    { key: "well", x: 19, y: 12 }, { key: "boathouse", x: 31, y: 24 },
  ],
  warps: [
    { x: 17, y: 29, to: "route_9", toX: 14, toY: 1, facing: "down" },
    { x: 18, y: 29, to: "route_9", toX: 15, toY: 1, facing: "down" },
    { x: 35, y: 17, to: "bloom_lake", toX: 1, toY: 17, facing: "right" },
    { x: 35, y: 18, to: "bloom_lake", toX: 1, toY: 18, facing: "right" },
    { x: 6, y: 11, to: "larchmere_greenhouse", toX: 5, toY: 7, facing: "up" },
    { x: 13, y: 11, to: "larchmere_market", toX: 6, toY: 7, facing: "up" },
    { x: 26, y: 9, to: "larchmere_conservatory", toX: 7, toY: 18, facing: "up" },
    { x: 26, y: 22, to: "larchmere_lodge", toX: 6, toY: 10, facing: "up" },
  ],
  npcs: [],
  signs: [{ x: 17, y: 15, text: "LARCHMERE, where the larches turn gold. BLOOM LAKE: east, past the LODGE." }],
  triggers: [
    { x: 26, y: 10, script: "ch7_cons7_door", when: when({ lake_calmed: false }) },
    // The chalets are private homes, each with its own Larchmere door script (lm_door_1..4).
    { x: 3, y: 5, script: "lm_door_1" }, { x: 9, y: 5, script: "lm_door_2" },
    { x: 4, y: 22, script: "lm_door_3" }, { x: 10, y: 22, script: "lm_door_4" },
  ],
  onEnter: "ch7_town_enter",
};
