import type { MapDef } from "../../contracts";
import { OUTDOOR } from "../build";

export const route_12: MapDef = {
  id: "route_12", name: "ROUTE 12", outdoor: true, music: "route",
  // A broken, windswept plateau: red sandstone gorges, baked clay, sand drifts
  // and scrub; grey scree round the boulder pits and the warden's cleft.
  border: "red_rock",
  legend: { ...OUTDOOR, R: "red_rock", c: "cracked_earth", z: "scree", ",": "desert_scrub" },
  tiles: [
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
    "RzzzzzzzzzzzzzRccccRRRRzzccRRRRcccccRRRR",
    "RRRc....zzzRRzRcccccRRRzccccRRRccccccRRR",
    "cccB....zzRRRzRccccccRRcRccccRRcccccccRR",
    "RRRc.~~.zzzRzzRcccccccRRRcccccRccccccccR",
    "RRRRR~~RRRRRRRRc,,,cccRcccccccRcc,,,cccR",
    "Rzzz....zzzzzzRc,,,cccRccccRccRcc,,,cccR",
    "RRRRRøøRRRRRRRRc,,,cccRcccccccRcc,,,cccR",
    "RzzzRccRzzzzzzRc,,,cccRRRcccccRcc,,,cccR",
    "RzzzRzzRzzzzccRcccccRRRRRRcccRRccccccRRR",
    "RzzzRzzRzzzzcc<cccccRRRRccccRRRcccccRRRR",
    "RzzzccccccccccRccRccRRRcccccccRRccRccRRR",
    "RzzcccccccccscRccccccRRcccccccRRRccccccR",
    "RzccccRccccsscRRRcccccRcRcccRRRRRcsccccR",
    "RRRcccccccccscRRRRcsccRccccRRRRRcccccccR",
    "RRRRcccccccRccRRRcssccRccsccRRRcsssccRRR",
    "RRRRccccssccccRcccssccRcssscRRRccsscRRRR",
    "RRRcccccsscRRRRcccccccRcccccccRcccccRRRR",
    "RRcccccc,,,ccRRcsscccc<cccccccRccccccRRR",
    "Rccccccc,,,cccRcssscccRcccRcccRRcccccccR",
    "Rccsssss,,,ccRRcccccRcRcccccccRRRccccccR",
    "Rcscsssc,,,cRcRRcccRRcRcscccRcRcccccsscR",
    "RccRccccccccccRRRcccccRcssccRRRccccssscR",
    "RcccRRRcccccccRcccccccRccccccRRccccccccR",
    "RccRRRRRccccccRccccccRRc,,,cccRccccccccR",
    "RcccRRcccRRRRcRcccccRRRc,,,cccRccccccRcR",
    "RcccccccccRRRcRRccccccRc,,,ccc<ccccccccR",
    "RcscccccRcccccRRRccRccRc,,,cccRccccccccR",
    "RcsscccccsssscRRRRccccRcccccccRcccc...cc",
    "RcccccccccccccRRRcccRRRcccccccRccc.....R",
    "RRRcccRcccccccRccccRRRRRccccccRcc..vv..R",
    "RRRRcccccccRRRRcccccRRRRRcccRRRRc......R",
    "RRRRRcccccRRRRRcccccccRRRRccRRRRRc....cR",
    "RRRRRRcccRRRRRRccRccccRRRRRRRRRRRRcccRRR",
    "RRRRRRRRRRRRRRRcccccccRRRRRRRRRRRRRcRRRR",
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
  ],
  structures: [],
  warps: [
    { x: 39, y: 28, to: "sanguine_ridge", toX: 1, toY: 15, facing: "right" },
    { x: 0, y: 3, to: "council_arboretum", toX: 32, toY: 22, facing: "left" },
  ],
  npcs: [
    { id: "r12_crag", sprite: "hiker", x: 34, y: 23, facing: "left", trainer: "r12_crag", sight: 1 },
    { id: "r12_gorge", sprite: "hiker", x: 26, y: 28, facing: "left", trainer: "r12_gorge", sight: 1 },
    { id: "r12_kite", sprite: "birdwatcher", x: 26, y: 12, facing: "left", trainer: "r12_kite", sight: 1 },
    { id: "r12_rook", sprite: "birdwatcher", x: 18, y: 23, facing: "left", trainer: "r12_rook", sight: 1 },
    { id: "r12_sedge", sprite: "gardener", x: 18, y: 5, facing: "left", trainer: "r12_sedge", sight: 1 },
    { id: "r12_heath", sprite: "gardener", x: 9, y: 14, facing: "left", trainer: "r12_heath", sight: 1 },
    { id: "boulder_1", sprite: "boulder", x: 5, y: 8, facing: "up", pushable: true },
    { id: "boulder_2", sprite: "boulder", x: 6, y: 8, facing: "up", pushable: true },
    { id: "marks_warden", sprite: "gentleman", x: 3, y: 2, facing: "right", script: "ch10_marks_warden" },
  ],
  signs: [],
  triggers: [{ x: 1, y: 3, script: "ch10_marks_warden" }],
  hidden: [{ x: 35, y: 8, item: "rain_jar" }, { x: 25, y: 6, item: "glass_pod" }, { x: 10, y: 19, item: "compost" }],
  encounters: { grass: { rate: 12, slots: [
    { species: "dragon_sapling", minLevel: 44, maxLevel: 44, weight: 20 },
    { species: "lithops_pair", minLevel: 39, maxLevel: 39, weight: 20 },
    { species: "saguaro", minLevel: 48, maxLevel: 55, weight: 15 },
    { species: "larch", minLevel: 48, maxLevel: 55, weight: 15 },
    { species: "red_cedar", minLevel: 48, maxLevel: 55, weight: 10 },
    { species: "moss_campion", minLevel: 48, maxLevel: 55, weight: 10 },
    { species: "dragon_fruit", minLevel: 48, maxLevel: 55, weight: 10 },
  ] } },
};
