import type { MapDef } from "../../contracts";
import { OUTDOOR } from "../build";

export const route_9: MapDef = {
  id: "route_9", name: "ROUTE 9", outdoor: true, music: "alpine", ambient: "mist",
  border: "larch_tree",
  // Larch forest (T), then the scree slope (+, rock, turf terraces and ledges), then the snowy pass
  // (? snow and n snow grass, both grass encounters) between cliffs (A); a trodden scree track crosses it.
  legend: { ...OUTDOOR, T: "larch_tree", "+": "scree", n: "snow_grass" },
  tiles: [
    "AAAAAAAAAAAAAA++AAAAAAAAAAAAAA",
    "AAA???AA??AAA?++???AAAA?????AA",
    "AA???nnn????A?++????AA???nnn?A",
    "A???nnnnn?????++nn????nnnnnn?A",
    "A????nnn????++++???????nnnn??A",
    "AA??????nn?++???????????????AA",
    "AAA?????nnn++??nnnn?????AAA??A",
    "AA?A??AA?n?++??nnnnn???AAAA??A",
    "A?????AA???+++??nnn??????A???A",
    "A????n??????+A???????????nn??A",
    "A??nnnn??????++?????nnnn?nnn?A",
    "A?nnnnnn??????++???nnnnnn????A",
    "A??nnnnA??????++????nnnn?AA??A",
    "AA????????????++?AA?????AAAA?A",
    "AAA??????????++??AA???????AA?A",
    "A?nn??AAAA???++??nnnn????????A",
    "A?nnnAAAAA??++??nnnnnn??nnn??A",
    "A?nn??AAnnn?++???nnnn??nnnnn?A",
    "AA??????nn??++????nnn??nAAnn?A",
    "AAA?????????++????????????nn?A",
    "AAAAA+++++++++++++++++++++AAAA",
    "AAA++++++o.++++++++++++.oo++AA",
    "A++++++++.....++++++.....++++A",
    "A+++AAA+..vvvv++++...vvvvv+++A",
    "A+++AAA++++++++++++++++++++o.A",
    "A++++++++++o.++++++++++++++..A",
    "A++++++++++..++++AAAA++++++++A",
    "A+++++++++++++++AAAAAA++++o++A",
    "A.....++++.....+++++++++++..+A",
    "Avvvvv++++vvvvv++++++++++++++A",
    "A++++++++++++++++++++++AA+++AA",
    "A+++oo+++++++++++++++++AAA+++A",
    "A++++.+++++AA+++++++++++++++TA",
    "AT++++++++AAAA++++++++++++++TT",
    "TTTTTTTTTTTT.++::++++TTTTTTTTT",
    "TTTTTTTTTTTTT..::..TTTTTTTTTTT",
    "TTTTTTTTTTTTT..::...TTT...TTTT",
    "TTTT....TTTTT..::..........TTT",
    "TTT.4.5..TTT...::...,,,,,,..TT",
    "TTT......TTT...::..T,,,,,,,.TT",
    "TTT.3.....:::::::..T,,,,,,,.TT",
    "TTTT......:::::TT..T,,,,,,..TT",
    "TTTT,,,,..::TTTTT...,,,,,..TTT",
    "TTT,,,,,,.::TTTTTT.........TTT",
    "TTT,,,,,,.::TTTTTT..y*..3TTTTT",
    "TTT,,,,,..::...TTTT....TTTTTTT",
    "TTTT,,,...::....TTTTTTTTTTTTTT",
    "TTTTT.....:::::.TTTTTTTTTTTTTT",
    "TTTTTTTT.TT..:::..TTTTTTTTTTTT",
    "TTTTTTTTTTT...::...TTT..TTTTTT",
    "TTTT.,,,TTT...::..T..,,,,.TTTT",
    "TTT..,,,,.....::.....,,,,,.TTT",
    "TTT.,,,,,..y..::..*f.,,,,..TTT",
    "TTTT.,,,.....S::.......,,.TTTT",
    "TTTTT.........::.........TTTTT",
    "TTTTTTTTTTTTTT::TTTTTTTTTTTTTT",
  ],
  structures: [],
  warps: [
    { x: 14, y: 55, to: "cedarhallow", toX: 17, toY: 2, facing: "down" },
    { x: 14, y: 0, to: "larchmere", toX: 17, toY: 28, facing: "up" },
    { x: 15, y: 0, to: "larchmere", toX: 18, toY: 28, facing: "up" },
  ],
  npcs: [
    { id: "climber_ridge", sprite: "hiker", x: 10, y: 45, facing: "right", trainer: "climber_ridge", sight: 2 },
    { id: "climber_scree", sprite: "hiker", x: 20, y: 29, facing: "left", trainer: "climber_scree", sight: 2 },
    { id: "skier_frost", sprite: "birdwatcher", x: 9, y: 14, facing: "right", trainer: "skier_frost", sight: 2 },
    { id: "skier_drift", sprite: "birdwatcher", x: 20, y: 7, facing: "left", trainer: "skier_drift", sight: 2 },
    { id: "mountaineer", sprite: "hiker", x: 8, y: 39, facing: "down", script: "q_lost_climber" },
  ],
  hidden: [{ x: 8, y: 8, item: "climber_pack" }, { x: 23, y: 11, item: "rain_jar" }],
  signs: [{ x: 13, y: 53, text: "ROUTE 9. The LARCH PASS climbs north to LARCHMERE." }], triggers: [],
  encounters: { grass: { rate: 10, slots: [
    { species: "larch_seedling", weight: 25, minLevel: 32, maxLevel: 33 },
    { species: "campion_cushion", weight: 25, minLevel: 29, maxLevel: 29 },
    { species: "edelweiss_bud", weight: 20, minLevel: 31, maxLevel: 31 },
    { species: "holly", weight: 10, minLevel: 32, maxLevel: 35 },
    { species: "peppermint", weight: 10, minLevel: 32, maxLevel: 35 },
    { species: "snowdrop_bulb", weight: 10, minLevel: 32, maxLevel: 35 },
  ] } },
};
