import type { MapDef } from "../../contracts";
import { OUTDOOR } from "../build";

export const route_8: MapDef = {
  id: "route_8", name: "ROUTE 8", outdoor: true, music: "route", ambient: "none",
  border: "volcanic_rock", legend: { ...OUTDOOR, ".": "salt_flat", A: "volcanic_rock", "=": "pier", e: "seagrass_bed", R: "tide_pool" },
  tiles: [
    "AA~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~AA",
    "AA~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~AA",
    "AA~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~AA",
    "AA~~~~~~~~~~~~~~~~~~~~~eeeee~~~~~~~~~~AA",
    "AA~~~~~~~~~~~~~~~~~~~~eeeeeee~~~~~~~~~AA",
    "AA~~~~~~~~~~~~~~~~~~~~eeeeeee~~~~~~~~~AA",
    "AA~~~ssssssssss~~~~~~~~eeeee~~~~~~~~~~AA",
    "AA~~~s........s~~~~~~~~~~~~~~~~~~~~~~~AA",
    "AA~~Rs........s~~~~~~~~~~~~~~~~~~~~~~~AA",
    "AA~~Rs........s~R~~~~~~~~~~~~~~~~~~~~~AA",
    "AA~~~s........s~R~~~~~~~~~~~~~~~~~~~~~AA",
    "AA~~~s........s~~~~~~~~~~~~~~~~~~~~~~~AA",
    "AA~~~ssssssssss~~~~~~~~~~~~~~~~~~~~~~~AA",
    "AA~~~~~~~~==~~~~~~~~~~~~~~~~~~~~~~~~~~AA",
    "AA~~eeeee~==~~~~~~~~~~~~~~~~~~~~~~~~~~AA",
    "AA~eeeeeee~~~~~~~~~~~~~~~~~~~~~~~~~~~~AA",
    "AA~eeeeeee~~~~~~~~~~~~~~~~~~~~~~~~~~~~AA",
    "AA~~eeeee~~~~~~~~~~~~~sssssssssss~~~~~AA",
    "AA~~~~~~~~~~~~~~~~~~~~s.........s~~~~~AA",
    "AA~~~~~~~~~~~~~~~~~~~Rs.........s~~~~~AA",
    "AA~~~~~~~~~~~~~~~~~~~Rs.........s~~~~~AA",
    "AA~~~~~~~~~~~~~~~~~~~~s.........s~R~~~AA",
    "AA~~~~~~~~~~~~~~~~~~~~s.........s~R~~~AA",
    "AA~~~~~~~~~~~~~~~~~~~~sssssssssss~~~~~AA",
    "AA~~~~~~~~~~~~~~~~~~~~~~~~~==~~~~~~~~~AA",
    "AA~~~~~~~~~~~~~~~~~eeeee~~~==~~~~~~~~~AA",
    "AA~~~~~~~~~~~~~~~~eeeeeee~~~~~~~~~~~~~AA",
    "AA~~~~~~~~~~~~~~~~eeeeeee~~~~~~~~~~~~~AA",
    "AA~~~~~~~~~~~~~~~~~eeeee~~~~~~~~~~~~~~AA",
    "AA~~~ssssssssss~~~~~~~~~~~~~~~~~~~~~~~AA",
    "AA~~~s........s~~~~~~~~~~~~~~~~~~~~~~~AA",
    "AA~~Rs........s~~~~~~~~~~~~~~~~~~~~~~~AA",
    "AA~~Rs........s~~~~~~~~~~~eeeee~~~~~~~AA",
    "AA~~~s........s~~~~~~~~~~eeeeeee~~~~~~AA",
    "AA~~~s........s~~~~~~~~~~eeeeeee~~~~~~AA",
    "AA~~~ssssssssss~~~~~~~~~~~eeeee~~~~~~~AA",
    "AA~~~~~~~~==~~~~~~~~~~~~~~~~~~~~~~~~~~AA",
    "AA~~~~~~~~==~~~~~~~~~~~~~~~~~~~~~~~~~~AA",
    "AA~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~AA",
    "AA~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~AA",
  ],
  structures: [],
  warps: [
    { x: 18, y: 0, to: "saltmarsh_harbour", toX: 18, toY: 28, facing: "up" },
    { x: 19, y: 0, to: "saltmarsh_harbour", toX: 19, toY: 28, facing: "up" },
    { x: 18, y: 39, to: "driftseed_isle", toX: 16, toY: 1, facing: "down" },
    { x: 19, y: 39, to: "driftseed_isle", toX: 17, toY: 1, facing: "down" },
  ],
  npcs: [
    { id: "sailor_kelp", sprite: "sailor", x: 7, y: 8, facing: "right", trainer: "sailor_kelp", sight: 2 },
    { id: "sailor_brine", sprite: "sailor", x: 12, y: 10, facing: "left", trainer: "sailor_brine", sight: 2 },
    { id: "diver_coral", sprite: "diver", x: 25, y: 20, facing: "right", trainer: "diver_coral", sight: 2 },
    { id: "diver_shoal", sprite: "diver", x: 8, y: 32, facing: "right", trainer: "diver_shoal", sight: 2 },
    { id: "survey_assistant", sprite: "researcher", x: 30, y: 22, facing: "up", script: "q_seagrass_survey" },
  ],
  signs: [], triggers: [],
  hidden: [{ x: 13, y: 7, item: "glass_pod" }, { x: 12, y: 34, item: "rain_jar" }],
  encounters: { water: { rate: 10, slots: [
    { species: "seagrass_shoot", minLevel: 26, maxLevel: 27, weight: 45 },
    { species: "mangrove_propagule", minLevel: 23, maxLevel: 23, weight: 30 },
    { species: "giant_water_lily", minLevel: 26, maxLevel: 30, weight: 10 },
    { species: "eelgrass", minLevel: 28, maxLevel: 30, weight: 15 },
  ] } },
};
