import type { MapDef } from "../../contracts";
import { OUTDOOR } from "../build";

export const route_7: MapDef = {
  id: "route_7", name: "ROUTE 7", outdoor: true, music: "route", ambient: "mist",
  border: "mangrove_roots", legend: { ...OUTDOOR, ".": "salt_flat", "@": "salt_flat", T: "mangrove_roots" },
  tiles: [
    "TTTTTTTTTTTTTT::TTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTT::TTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTT::TTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTT::TTTTTTTTTTTTTT",
    "TT............::............TT",
    "TT............::............TT",
    "TT..,,,,,,,...::............TT",
    "TT..,,,,,,,...::............TT",
    "TT..,,,,,,,...::............TT",
    "TT..,,,,,,,...::............TT",
    "TT..,,,,,,,...::............TT",
    "TT..,,,,,,,...::............TT",
    "TT............::............TT",
    "TT............::............TT",
    "TTqqqqqqqqqq..::............TT",
    "TT~~~~~~~~~~~~==~~~~~~~~~~~~TT",
    "TT~~~~~~~~~~~~==~~~~~~~~~~~~TT",
    "TT~~~~~~~~~~~~==~~~~~~~~~~~~TT",
    "TT~~~~~~~~~~~~==~~~~~~~~~~~~TT",
    "TT~~~~~~~~~~~~==~~~~~~~~~~~~TT",
    "TT............::..qqqqqqqqqqTT",
    "TT............::............TT",
    "TT............::...,,,,,,,..TT",
    "TT............::...,,,,,,,..TT",
    "TT............::...,,,,,,,..TT",
    "TT............::...,,,,,,,..TT",
    "TT............::...,,,,,,,..TT",
    "TT............::...,,,,,,,..TT",
    "TT............::............TT",
    "TTqqqqqqqqqq..::............TT",
    "TT~~~~~~~~~~~~==~~~~~~~~~~~~TT",
    "TT~~~~~~~~~~~~==~~~~~~~~~~~~TT",
    "TT~~~~~~~~~~~~==~~~~~~~~~~~~TT",
    "TT~~~~~~~~~~~~==~~~~~~~~~~~~TT",
    "TT~~~~~~~~~~~~==~~~~~~~~~~~~TT",
    "TT............::..qqqqqqqqqqTT",
    "TT............::............TT",
    "TT............::............TT",
    "TT............::............TT",
    "TT..,,,,,,,...::............TT",
    "TT..,,,,,,,...::............TT",
    "TT..,,,,,,,...::............TT",
    "TT..,,,,,,,...::............TT",
    "TT..,,,,,,,...::............TT",
    "TT..,,,,,,,...::............TT",
    "TT............::............TT",
    "TTTTTTTTTTTTTT::TTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTT::TTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTT::TTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTT::TTTTTTTTTTTTTT",
  ],
  structures: [],
  warps: [
    { x: 14, y: 0, to: "fallowfield", toX: 16, toY: 22, facing: "up" },
    { x: 15, y: 0, to: "fallowfield", toX: 16, toY: 22, facing: "up" },
    { x: 14, y: 49, to: "saltmarsh_harbour", toX: 18, toY: 1, facing: "down" },
    { x: 15, y: 49, to: "saltmarsh_harbour", toX: 19, toY: 1, facing: "down" },
  ],
  npcs: [
    { id: "angler_reed", sprite: "angler", x: 11, y: 12, facing: "right", trainer: "angler_reed", sight: 3 },
    { id: "angler_moss", sprite: "angler", x: 19, y: 26, facing: "left", trainer: "angler_moss", sight: 3 },
    { id: "birder_tern", sprite: "birdwatcher", x: 11, y: 42, facing: "right", trainer: "birder_tern", sight: 3 },
  ],
  hidden: [{ x: 7, y: 13, item: "spring_water" }, { x: 23, y: 40, item: "glass_pod" }],
  signs: [], triggers: [],
  encounters: { grass: { rate: 12, slots: [
    { species: "mangrove_propagule", minLevel: 23, maxLevel: 23, weight: 30 },
    { species: "cattail", minLevel: 24, maxLevel: 27, weight: 20 },
    { species: "sundew", minLevel: 24, maxLevel: 27, weight: 15 },
    { species: "pear_pad", minLevel: 21, maxLevel: 21, weight: 15 },
    { species: "seagrass_shoot", minLevel: 24, maxLevel: 27, weight: 10 },
    { species: "mint_sprig", minLevel: 15, maxLevel: 15, weight: 10 },
  ] } },
};
