import type { MapDef } from "../../contracts";
import { OUTDOOR, when } from "../build";

export const route_11: MapDef = {
  id: "route_11", name: "ROUTE 11", outdoor: true, music: "route", ambient: "none",
  border: "cliff", legend: OUTDOOR,
  tiles: [
    "AAAAAAAAAAAAA::AAAAAAAAAAAAA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Ass,,,,,,ssss::ssssssssssssA",
    "Ass,,,,,,ssss::ssssssssssssA",
    "Ass,,,,,,ssss::ssssssssssssA",
    "Ass,,,,,,ssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssss::::::::ssssssssssssA",
    "AAAAAAA::AAAAAAAAAAAAAAAAAAA",
    "Assssss::::::::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssss,,,,,sssA",
    "Assssssssssss::ssss,,,,,sssA",
    "Assssssssssss::ssss,,,,,sssA",
    "Assssssssssss::ssss,,,,,sssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "AAAAAAAAAAAAA::AAAAAAAAAAAAA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssAAAAAAAsA",
    "Assssssssssss::ssssAsssssAsA",
    "Ass,,,,,,ssss::ssssAsssssAsA",
    "Ass,,,,,,ssss::ssss<sssssAsA",
    "Ass,,,,,,ssss::ssssAsssssAsA",
    "Ass,,,,,,ssss::ssssAsssssAsA",
    "Assssssssssss::ssssAAAAAAAsA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::::::::ssssssA",
    "AAAAAAAAAAAAAAAAAAA::AAAAAAA",
    "Assssssssssss::::::::ssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssvvss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "Assssssssssss::ssssssssssssA",
    "AAAAAAAAAAAAA::AAAAAAAAAAAAA",
  ],
  structures: [],
  warps: [
    { x: 13, y: 55, to: "thistledown", toX: 14, toY: 1, facing: "down" },
    { x: 14, y: 55, to: "thistledown", toX: 15, toY: 1, facing: "down" },
    { x: 13, y: 0, to: "sanguine_ridge", toX: 15, toY: 26, facing: "up" },
    { x: 14, y: 0, to: "sanguine_ridge", toX: 16, toY: 26, facing: "up" },
  ],
  npcs: [
    { id: "climber_red", sprite: "hiker", x: 11, y: 48, facing: "right", trainer: "climber_red", sight: 2 },
    { id: "climber_ochre", sprite: "hiker", x: 15, y: 39, facing: "left", trainer: "climber_ochre", sight: 2 },
    { id: "ranger_flint", sprite: "birdwatcher", x: 11, y: 21, facing: "right", trainer: "ranger_flint", sight: 2 },
    { id: "ranger_shale", sprite: "birdwatcher", x: 15, y: 7, facing: "left", trainer: "ranger_shale", sight: 2 },
    { id: "bram", sprite: "bram", x: 15, y: 27, facing: "down", script: "rival_5", visibleWhen: when({ rival_5_done: false }) },
  ],
  hidden: [{ x: 23, y: 35, item: "rain_jar" }],
  signs: [], triggers: [{ x: 13, y: 29, w: 2, script: "rival_5", when: when({ rival_5_done: false }) }],
  // Numeric growth triggers override the route's ordinary 42–46 range.
  encounters: { grass: { rate: 12, slots: [
    { species: "lithops_pair", minLevel: 39, maxLevel: 39, weight: 25 },
    { species: "dragon_seedling", minLevel: 29, maxLevel: 29, weight: 25 },
    { species: "pitaya_cutting", minLevel: 37, maxLevel: 37, weight: 20 },
    { species: "snapdragon_sprout", minLevel: 21, maxLevel: 21, weight: 15 },
    { species: "saguaro_column", minLevel: 39, maxLevel: 39, weight: 15 },
  ] } },
};
