import type { MapDef } from "../../contracts";
import { OUTDOOR } from "../build";

export const route_12: MapDef = {
  id: "route_12", name: "ROUTE 12", outdoor: true, music: "route",
  border: "cliff", legend: OUTDOOR,
  tiles: [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AsssssssssssssAsssssssAsssssssAssssssssA",
    "AAAsssssssssssAsssssssAsssssssAssssssssA",
    "::::ssssssssssAsssssssAsssssssAssssssssA",
    "AAAsssssssssssAsssssssAsssssssAssssssssA",
    "AsssssssssssssAs,,,sssAsssssssAss,,,sssA",
    "AsssssssssssssAs,,,sssAsssssssAss,,,sssA",
    "AAAAAøøAAAAAAAAs,,,sssAsssssssAss,,,sssA",
    "AsssA::AssssssAs,,,sssAsssssssAss,,,sssA",
    "AsssA::AssssssAsssssssAsssssssAssssssssA",
    "AsssA::Assss::<::sssssAsssssssAssssssssA",
    "AsssssssssssssAsssssssAsssssssAssssssssA",
    "AsssssssssssssAsssssssAsssssssAssssssssA",
    "AsssssssssssssAsssssssAsssssssAssssssssA",
    "AsssssssssssssAsssssssAsssssssAssssssssA",
    "AsssssssssssssAsssssssAsssssssAssssssssA",
    "AsssssssssssssAsssssssAsssssssAssssssssA",
    "AsssssssssssssAsssssssAsssssssAssssssssA",
    "Asssssss,,,sssAsssss::<::sssssAssssssssA",
    "Asssssss,,,sssAsssssssAsssssssAssssssssA",
    "Asssssss,,,sssAsssssssAsssssssAssssssssA",
    "Asssssss,,,sssAsssssssAsssssssAssssssssA",
    "AsssssssssssssAsssssssAsssssssAssssssssA",
    "AsssssssssssssAsssssssAsssssssAssssssssA",
    "AsssssssssssssAsssssssAs,,,sssAssssssssA",
    "AsssssssssssssAsssssssAs,,,sssAssssssssA",
    "AsssssssssssssAsssssssAs,,,s::<::ssssssA",
    "AsssssssssssssAsssssssAs,,,sssAssssssssA",
    "AsssssssssssssAsssssssAsssssssAssssssss:",
    "AsssssssssssssAsssssssAsssssssAssssssssA",
    "AsssssssssssssAsssssssAsssssssAssssvvssA",
    "AsssssssssssssAsssssssAsssssssAssssssssA",
    "AsssssssssssssAsssssssAsssssssAssssssssA",
    "AsssssssssssssAsssssssAsssssssAssssssssA",
    "AsssssssssssssAsssssssAsssssssAssssssssA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  ],
  structures: [],
  warps: [
    { x: 39, y: 28, to: "sanguine_ridge", toX: 1, toY: 15, facing: "right" },
    { x: 0, y: 3, to: "council_arboretum", toX: 32, toY: 22, facing: "left" },
  ],
  npcs: [
    { id: "r12_crag", sprite: "hiker", x: 34, y: 23, facing: "left", trainer: "r12_crag", sight: 1 },
    { id: "r12_gorge", sprite: "hiker", x: 26, y: 28, facing: "left", trainer: "r12_gorge", sight: 1 },
    { id: "r12_kite", sprite: "birdwatcher", x: 26, y: 12, facing: "left", trainer: "r12_kite", sight: 1 },
    { id: "r12_rook", sprite: "birdwatcher", x: 18, y: 23, facing: "left", trainer: "r12_rook", sight: 1 },
    { id: "r12_sedge", sprite: "gardener", x: 18, y: 5, facing: "left", trainer: "r12_sedge", sight: 1 },
    { id: "r12_heath", sprite: "gardener", x: 9, y: 14, facing: "left", trainer: "r12_heath", sight: 1 },
    { id: "boulder_1", sprite: "boulder", x: 5, y: 8, facing: "up", pushable: true },
    { id: "boulder_2", sprite: "boulder", x: 6, y: 8, facing: "up", pushable: true },
    { id: "marks_warden", sprite: "gentleman", x: 3, y: 2, facing: "right", script: "ch10_marks_warden" },
  ],
  signs: [],
  triggers: [{ x: 2, y: 3, script: "ch10_marks_warden" }],
  hidden: [{ x: 35, y: 8, item: "rain_jar" }, { x: 25, y: 6, item: "glass_pod" }, { x: 10, y: 19, item: "compost" }],
  encounters: { grass: { rate: 12, slots: [
    { species: "dragon_sapling", minLevel: 44, maxLevel: 44, weight: 20 },
    { species: "lithops_pair", minLevel: 39, maxLevel: 39, weight: 20 },
    { species: "saguaro", minLevel: 48, maxLevel: 55, weight: 15 },
    { species: "larch", minLevel: 48, maxLevel: 55, weight: 15 },
    { species: "red_cedar", minLevel: 48, maxLevel: 55, weight: 10 },
    { species: "moss_campion", minLevel: 48, maxLevel: 55, weight: 10 },
    { species: "dragon_fruit", minLevel: 48, maxLevel: 55, weight: 10 },
  ] } },
};
