import type { MapDef } from "../../contracts";
import { OUTDOOR, when } from "../build";

export const saltmarsh_harbour: MapDef = {
  id: "saltmarsh_harbour", name: "SALTMARSH HARBOUR", outdoor: true, music: "small_town", ambient: "none",
  border: "mangrove_roots", legend: { ...OUTDOOR, ".": "salt_flat", "@": "salt_flat", T: "mangrove_roots", "=": "pier", R: "tide_pool", g: "dry_grass", z: "shell_scatter", D: "driftwood", K: "beach_rock", F: "fishing_net" },
  tiles: [
    "TTTTTTTTTTTTTTTTTT::TTTTTTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTTTT::TTTTTTTTTTTTTTTTTTTT",
    "~~zzzz............::........zzzzzzzzzz~~",
    "~~zzzzK.gggggggK.S::........zzzzzzzzzz~~",
    "~~zzzz..ggggggg...::.........glggg.zzz~~",
    "~RzDzz...glggg....::..@@@@@@.ggggg.zKz~~",
    "~Rzzzzgggggggg....::..@@@@@@.ggg...zzz~~",
    "~~zzzzggggg.......::..@@@@@@.ggD.@@@zz~~",
    "~~zz..............::..@@@@@@.....@@@zz~~",
    "~~zz@@@@....@@@@..::.....:..ggg..@@@Kz~~",
    "~~zz@@@@..8.@@@@..::gyy..:..ggg..@@@zz~~",
    "~~zz@@@@..7.@@@@..::yggzz:...9....!zzz~~",
    "~~zz..:..6...:....::.9.zz:..::::...zlz~~",
    "~~...:::::::::::::::::::NN:::::::::...~~",
    "~~...::::::::::::::::::::::::::::::...R~",
    "~~zzzzggg...::ggg.::::6.....9..zzzzzzzR~",
    "~~zzzzKgg...::gF7.::::.gggggg..zzzzzzz~~",
    "~~zDzzgg....::....::::.gggggg..zzzzzzz~~",
    "~~zzzzggF...::....::::....ggggDzzzzzzz~~",
    "~~zzzzzz87z.::....::::.F87zzzzzzzzKzzz~~",
    "~~zzzzzzzzz.::....::::....zzzzzzzzzzzz~~",
    "~~~~~~~~~~RR==~~~~~~==~~~~~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~==~~~~~~==~~~~~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~==~~~~~~==RR~~~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~==~~~~~~==~~~~~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~==RR~~~~==~~~~~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~==~~~~~~~~~~~~~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
  ],
  structures: [
    { key: "greenhouse", x: 4, y: 9 }, { key: "harbour_house", x: 12, y: 9 },
    { key: "tide_conservatory", x: 22, y: 5 }, { key: "lantern_tree", x: 33, y: 7 },
  ],
  warps: [
    { x: 18, y: 0, to: "route_7", toX: 14, toY: 48, facing: "up" },
    { x: 19, y: 0, to: "route_7", toX: 15, toY: 48, facing: "up" },
    { x: 18, y: 29, to: "route_8", toX: 18, toY: 1, facing: "down" },
    { x: 19, y: 29, to: "route_8", toX: 19, toY: 1, facing: "down" },
    { x: 6, y: 11, to: "saltmarsh_greenhouse", toX: 5, toY: 7, facing: "up" },
    { x: 13, y: 11, to: "saltmarsh_market", toX: 6, toY: 7, facing: "up" },
    { x: 25, y: 8, to: "saltmarsh_conservatory", toX: 7, toY: 16, facing: "up" },
  ],
  npcs: [
    { id: "doctor", sprite: "calloway", script: "ch6_doctor", x: 12, y: 23, facing: "up", movement: "static", visibleWhen: when({ ch6_doctor_met: false }) },
    { id: "grunt_dock_1", sprite: "grunt", x: 11, y: 20, facing: "up", trainer: "grunt_dock_1", sight: 2, visibleWhen: when({ ch6_doctor_met: true, beat_grunt_dock_1: false }) },
    { id: "grunt_dock_2", sprite: "grunt", x: 15, y: 20, facing: "up", trainer: "grunt_dock_2", sight: 2, visibleWhen: when({ ch6_doctor_met: true, beat_grunt_dock_2: false }) },
    { id: "reyes_point", sprite: "reyes", x: 32, y: 12, facing: "left", script: "ch6_reyes_point", visibleWhen: when({ lantern_healed: false }) },
  ],
  // Interactable plaque: a static sign would consume A before its script.
  signs: [{ x: 17, y: 3, text: "SALTMARSH HARBOUR. Docks to the south." }],
  triggers: [
    { x: 12, y: 20, w: 2, script: "ch6_doctor", when: when({ ch6_arrived: true, ch6_doctor_met: false }) },
    { x: 34, y: 11, script: "ch6_lantern_tree" },
    { x: 25, y: 9, script: "ch6_cons5_door", when: when({ lantern_healed: false }) },
  ],
  onEnter: "ch6_town_enter",
};
