import type { MapDef } from "../../contracts";
import { OUTDOOR, when } from "../build";

export const sanguine_ridge: MapDef = {
  id: "sanguine_ridge", name: "SANGUINE RIDGE", outdoor: true, music: "small_town", ambient: "none",
  border: "cliff", legend: OUTDOOR,
  tiles: [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "Assssssssssssss::ssssssssssssssA",
    "Assssssssssssss::ssssssssssssssA",
    "Ass@@@sssssssss::ssssssssssssssA",
    "Ass@@@sssssssss::ssssssssssssssA",
    "Ass@@@sssssssss::sssss@@@@@@sssA",
    "Assssssssssssss::sssss@@@@@@sssA",
    "Assssssssssssss::sssss@@@@@@sssA",
    "Assssssssssssss::sssss@@@@@@sssA",
    "Asss@@@@sssssss::ssssssssssssssA",
    "Asss@@@@sssssss::ssssssssssssssA",
    "Asss@@@@sssssss::ssssssssssssssA",
    "Assssssssssssss::ssssssssssssssA",
    "Assssssssssssss::ssssssssssssssA",
    "Assssssssssssss::ssssssssssssssA",
    "N:::::::::::::::sssssssssssssssA",
    "Assssssssssssss::ssssssssssssssA",
    "Assssssssssssss::ssssssssssssssA",
    "Assssssssssssss::ssssssssssssssA",
    "Assssssssssssss::sssss@@@ssssssA",
    "Assss@@@sssssss::sssss@@@ssssssA",
    "Assss@@@sssssss::sssss@@@ssssssA",
    "Assss@@@sssssss::ssssssssssssssA",
    "Assssssssssssss::ssssssssssssssA",
    "Assssssssssssss::ssssssssssssssA",
    "Assssssssssssss::ssssssssssssssA",
    "Assssssssssssss::ssssssssssssssA",
    "AAAAAAAAAAAAAAA::AAAAAAAAAAAAAAA",
  ],
  legendWhen: [{ when: when({ ch9_done: false }), legend: { N: "cliff" } }],
  structures: [
    { key: "greenhouse", x: 4, y: 9 }, { key: "conservatory", x: 22, y: 5 },
    { key: "big_oak", x: 3, y: 3 }, { key: "big_oak", x: 22, y: 19 }, { key: "big_oak", x: 5, y: 20 },
  ],
  warps: [
    { x: 0, y: 15, to: "route_12", toX: 38, toY: 28, facing: "left" },
    { x: 15, y: 27, to: "route_11", toX: 13, toY: 1, facing: "down" },
    { x: 16, y: 27, to: "route_11", toX: 14, toY: 1, facing: "down" },
    { x: 6, y: 11, to: "sanguine_greenhouse", toX: 5, toY: 7, facing: "up" },
    { x: 25, y: 8, to: "sanguine_conservatory", toX: 8, toY: 18, facing: "up" },
  ],
  npcs: [], signs: [],
  triggers: [{ x: 1, y: 15, script: "ch10_west_gate", when: when({ ch9_done: false }) }, { x: 25, y: 9, script: "ch9_cons8_door", when: when({ rival_5_done: false }) }],
  onEnter: "ch9_end",
};
