import type { MapDef } from "../../contracts";
import { LEGEND } from "../build";

export const sanguine_conservatory: MapDef = {
  id: "sanguine_conservatory", name: "CONSERVATORY", outdoor: false, music: "conservatory", ambient: "none",
  border: "void", legend: LEGEND,
  tiles: [
    "WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW",
    "WWWWWWWtttWWWWWWWW",
    "WWWWWWWtttWWWWWWWW",
    "WWWWWWWtttWWWWWWWW",
    "WWWWWWWtttWWWWWWWW",
    "WWWWWWWWøWWWWWWWWW",
    "WWWWWWWtttWWWWWWWW",
    "WWWWWWWWttWWWWWWWW",
    "WWWWWWWWttWWWWWWWW",
    "WWWWWWWWøWWWWWWWWW",
    "WWWWWWWtttWWWWWWWW",
    "WWWWWWWWttWWWWWWWW",
    "WWWWWWWWtWWWWWWWWW",
    "WWWWWWWWøWWWWWWWWW",
    "WWWWWWWtttWWWWWWWW",
    "WWWWWtttttWWWWWWWW",
    "WWWWWtttttWWWWWWWW",
    "WWWWWtttttWWWWWWWW",
    "WWWWWWWWEWWWWWWWWW",
  ],
  structures: [],
  warps: [{ x: 8, y: 19, to: "sanguine_ridge", toX: 25, toY: 9, facing: "down" }],
  npcs: [
    { id: "boulder_1", sprite: "boulder", x: 8, y: 15, facing: "up", pushable: true },
    { id: "boulder_2", sprite: "boulder", x: 8, y: 11, facing: "up", pushable: true },
    { id: "boulder_3", sprite: "boulder", x: 8, y: 7, facing: "up", pushable: true },
    { id: "boulder_spare", sprite: "boulder", x: 6, y: 17, facing: "right", pushable: true },
    { id: "jr_ember", sprite: "gardener", x: 9, y: 17, facing: "left", trainer: "jr_ember", sight: 1 },
    { id: "jr_scale", sprite: "gardener", x: 9, y: 9, facing: "left", trainer: "jr_scale", sight: 1 },
    { id: "rook", sprite: "hollis", x: 8, y: 2, facing: "down", script: "rook" },
  ],
  signs: [], triggers: [],
};
